[package]
name = "rldevtut22"
version = "0.1.0"
authors = ["Peter Howell"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = "0.8.1"